FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Organicity Resource Directory API

Git the available resources for the 3 Organicity sites.

## Get all entities registered in all Organicity sites [/v1/entities]

### Get all entities availabe in the central resource directory [GET]

+ Response 200 (application/json)
    
        [
            {
                id: -659783864,
                uuid: "urn:oc:entity:patras:weatherstation:fixed:-578724766",
                name: "urn:oc:entity:patras:weatherstation:fixed:-578724766",
                last_reading_at: "2015-10-22T09:40Z",
                provider: {
                    id: 0,
                    uuid: "urn:oc:entity:patras",
                    username: "Patras",
                    avatar: "http://www.multistick.gr/files/images/dimos_patron.png",
                    url: "http://cti.gr",
                    joined_at: "",
                    location: {
                        city: "Patras",
                        country: "Greece",
                        country_code: "GR"
                    },
                    device_ids: [ ]
                },
                data: {
                    recorded_at: "2015-10-22T09:40Z",
                    location: {
                        latitude: 0,
                        longitude: 0,
                        city: null,
                        country_code: null,
                        country: null
                    },
                    attributes: [
                        {
                            id: 1303015757,
                            name: "atmosphericPressure",
                            unit: "bar",
                            updated_at: "2015-10-22T09:40Z",
                            attributes_id: "urn:oc:atributeType:atmosphericPressure",
                            value: 0,
                            prev_value: 0
                        },
                        {
                            id: -1915843409,
                            name: "rainfall",
                            unit: "mililiterPerHour",
                            updated_at: "2015-10-22T09:40Z",
                            attributes_id: "urn:oc:attributeTypes:rainfall",
                            value: 0,
                            prev_value: 0
                        }
                    ]
                },
                entities_type: null
            }
        ]